name: publish

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - uses: actions/setup-python@v4
        with:
          python-version: "3.7"

      - name: install dependencies
        run: |
          python3 -m pip install --upgrade pip

      - name: build & verify package
        run: |
          python3 setup.py install  # a simple test

          pip install -U build wheel check-wheel-contents twine
          python3 -m build --no-isolation
          check-wheel-contents dist/*.whl
          twine check --strict dist/*

      - name: upload
        if: ${{ github.event_name == 'push' }}
        run: twine upload -u __token__ -p "${{ secrets.PYPI_API_TOKEN }}" dist/*
